// ============================================================================
// DESIGN GENERATION VALIDATOR — Chat spec §58-60, §131
// AI output is untrusted input. Pipeline:
//   Gemini -> parse JSON -> schema validation -> structural validation
//     -> graph validation -> security validation -> (DB, by the worker)
// ============================================================================

import { z } from 'zod'
import { AppError, ERROR_CODES } from '../../utils/errors.js'

// Component metadata — mirrors the canvas block library so generated designs
// render identically to hand-built ones (frontend customBlock/customEdge).
export const NODE_TYPE_META = Object.freeze({
  client:          { label: 'Client',           icon: 'Globe',    category: 'frontend',    color: '#6366f1', cost: 0 },
  cdn:             { label: 'CDN',              icon: 'Globe',    category: 'network',     color: '#14b8a6', cost: 45 },
  'load-balancer': { label: 'Load Balancer',    icon: 'Shuffle',  category: 'network',     color: '#3b82f6', cost: 25 },
  'api-gateway':   { label: 'API Gateway',      icon: 'DoorOpen', category: 'network',     color: '#06b6d4', cost: 60 },
  service:         { label: 'Service',          icon: 'Server',   category: 'compute',     color: '#3b82f6', cost: 85 },
  database:        { label: 'Database',         icon: 'Database', category: 'data',        color: '#f97316', cost: 180 },
  cache:           { label: 'Cache',            icon: 'Zap',      category: 'data',        color: '#ef4444', cost: 60 },
  'message-queue': { label: 'Message Queue',    icon: 'Mail',     category: 'messaging',   color: '#eab308', cost: 55 },
  websocket:       { label: 'WebSocket Server', icon: 'Radio',    category: 'network',     color: '#ec4899', cost: 70 },
  'object-storage':{ label: 'Object Storage',   icon: 'HardDrive',category: 'data',        color: '#14b8a6', cost: 40 },
  storage:         { label: 'Object Storage',   icon: 'HardDrive',category: 'data',        color: '#14b8a6', cost: 40 },
  'external-api':  { label: 'External API',     icon: 'Plug',     category: 'integration', color: '#84cc16', cost: 0 },
})

export const ALLOWED_NODE_TYPES = Object.keys(NODE_TYPE_META)
export const ALLOWED_CONNECTION_TYPES = ['http', 'db', 'event', 'grpc', 'websocket']

// Security limits (spec §83).
export const LIMITS = Object.freeze({
  MAX_NODES: 60,
  MAX_EDGES: 120,
  MAX_NAME_LENGTH: 120,
  MAX_DESCRIPTION_LENGTH: 1000,
  MAX_LABEL_LENGTH: 80,
})

// ── Schema validation ───────────────────────────────────────────────────────

const rawNodeSchema = z.object({
  id: z.string().trim().min(1).max(64),
  type: z.string().trim().toLowerCase(),
  label: z.string().trim().min(1).max(LIMITS.MAX_LABEL_LENGTH).optional(),
  config: z.record(z.any()).optional(),
})

const rawEdgeSchema = z.object({
  source: z.string().trim().min(1).max(64),
  target: z.string().trim().min(1).max(64),
  connectionType: z.string().trim().toLowerCase().optional(),
})

const rawDesignSchema = z.object({
  name: z.string().trim().min(1),
  description: z.string().trim().max(LIMITS.MAX_DESCRIPTION_LENGTH).optional(),
  nodes: z.array(rawNodeSchema).min(1),
  edges: z.array(rawEdgeSchema).default([]),
})

// ── Full validation pipeline ────────────────────────────────────────────────

/**
 * Validate and normalize an AI-generated design.
 * @param {object} parsed — the parsed JSON from the AI
 * @returns {{ name, description, blocks, edges, cardPayload, stats }}
 * @throws {AppError} AI_INVALID_OUTPUT when validation fails
 */
export function validateGeneratedDesign(parsed) {
  const schema = rawDesignSchema.safeParse(parsed)
  if (!schema.success) {
    throw new AppError(ERROR_CODES.AI_INVALID_OUTPUT, 'The generated design failed schema validation.', {
      details: { issues: schema.error.issues.slice(0, 5) },
    })
  }
  const raw = schema.data

  if (raw.nodes.length > LIMITS.MAX_NODES) {
    throw new AppError(ERROR_CODES.AI_INVALID_OUTPUT, `Generated design exceeds ${LIMITS.MAX_NODES} node limit (${raw.nodes.length}).`)
  }

  // Structural: keep only allowed node types; enforce unique IDs.
  const seen = new Set()
  const nodes = []
  for (const node of raw.nodes) {
    if (!ALLOWED_NODE_TYPES.includes(node.type)) continue
    if (seen.has(node.id)) continue // duplicate node id — drop silently
    seen.add(node.id)
    nodes.push({
      id: node.id,
      type: node.type,
      label: (node.label || NODE_TYPE_META[node.type].label).slice(0, LIMITS.MAX_LABEL_LENGTH),
      config: node.config && typeof node.config === 'object' ? node.config : {},
    })
  }
  if (nodes.length === 0) {
    throw new AppError(ERROR_CODES.AI_INVALID_OUTPUT, 'The generated design contains no supported components.')
  }

  const name = raw.name.slice(0, LIMITS.MAX_NAME_LENGTH)
  const description = raw.description || 'Generated by Resonance AI Chat'

  // Graph validation (spec §60): edge endpoints exist, no self-loops,
  // duplicates dropped, allowed connection types, edge limit enforced.
  const nodeIds = new Set(nodes.map((n) => n.id))
  const edgeSeen = new Set()
  const edges = []
  for (const edge of raw.edges) {
    if (!nodeIds.has(edge.source) || !nodeIds.has(edge.target)) continue
    if (edge.source === edge.target) continue // self-loop rejection
    const key = `${edge.source}->${edge.target}`
    if (edgeSeen.has(key)) continue // duplicate edge
    edgeSeen.add(key)
    const connectionType = ALLOWED_CONNECTION_TYPES.includes(edge.connectionType || '')
      ? edge.connectionType
      : 'http'
    edges.push({ source: edge.source, target: edge.target, connectionType })
  }
  if (edges.length > LIMITS.MAX_EDGES) edges.length = LIMITS.MAX_EDGES

  // Security validation: strip anything that looks like embedded instructions
  // from user-visible strings (spec §61 — labels are untrusted data).
  const sanitize = (s) => s.replace(/[<>`]/g, '').trim()

  const positions = layoutPositions(nodes)
  const blocks = nodes.map((n) => ({
    type: n.type,
    label: sanitize(n.label),
    x: positions[n.id].x,
    y: positions[n.id].y,
    color: NODE_TYPE_META[n.type].color,
    config: n.config,
  }))

  const dbEdges = edges.map((e) => ({
    sourceId: e.source,
    targetId: e.target,
    connectionType: e.connectionType,
    animated: e.connectionType !== 'db',
  }))

  // Card payload — React-Flow shape so the chat generation card and the
  // Canvas Editor render the same design.
  const cardNodes = nodes.map((n, i) => ({
    id: n.id,
    type: 'customBlock',
    position: { x: positions[n.id].x, y: positions[n.id].y },
    data: {
      label: sanitize(n.label),
      type: n.type,
      icon: NODE_TYPE_META[n.type].icon,
      category: NODE_TYPE_META[n.type].category,
      color: NODE_TYPE_META[n.type].color,
      description: '',
      config: n.config,
      isCustom: false,
    },
  }))
  const cardEdges = edges.map((e, i) => ({
    id: `edge-${i + 1}`,
    type: 'customEdge',
    source: e.source,
    target: e.target,
    sourceId: e.source,
    targetId: e.target,
    animated: e.connectionType !== 'db',
    data: { connectionType: e.connectionType },
  }))

  const estimatedMonthlyCost = estimateMonthlyCost(nodes)

  return {
    name,
    description: sanitize(description),
    blocks,
    edges: dbEdges,
    cardPayload: {
      designId: null, // filled by the worker after the design row exists
      name,
      description,
      nodes: cardNodes,
      edges: cardEdges,
      nodeCount: nodes.length,
      edgeCount: edges.length,
      estimatedMonthlyCost,
    },
    stats: { nodeCount: nodes.length, edgeCount: edges.length },
  }
}

// ── Layout ──────────────────────────────────────────────────────────────────

const LAYER_BY_CATEGORY = { frontend: 0, network: 1, compute: 2, integration: 3, data: 3, messaging: 3 }

/**
 * Simple layered layout: components grouped by category rows, spread evenly.
 */
function layoutPositions(nodes) {
  const layers = new Map()
  for (const node of nodes) {
    const layer = LAYER_BY_CATEGORY[NODE_TYPE_META[node.type].category] ?? 2
    if (!layers.has(layer)) layers.set(layer, [])
    layers.get(layer).push(node)
  }
  const positions = {}
  for (const [layer, layerNodes] of layers.entries()) {
    layerNodes.forEach((node, i) => {
      positions[node.id] = {
        x: 80 + i * 280,
        y: 80 + layer * 200,
      }
    })
  }
  return positions
}

function estimateMonthlyCost(nodes) {
  const componentCost = nodes.reduce((sum, n) => sum + (NODE_TYPE_META[n.type]?.cost || 0), 0)
  return Math.round((componentCost + 40) / 10) * 10
}
